<a href="https://colab.research.google.com/github/sivasankar39/Numpy_Pandas_ClassActivity/blob/main/Numpy_Pandas_ClassActivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [2]:
import numpy as np
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
array2 = array.reshape(4,10)
array2

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [4]:
print(array2[3])

[40 41 42 43 44 45 46 47 48 49]


In [5]:
import numpy as np
array1 = np.full((3,3), 5)
print(array1)
array2 = np.arange(1,10)
print(array2)
array3 = array2.reshape(3,3)
print(array3)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
sum = array1 + array3
print(sum)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
product = array1 * array3
product

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
transpose = product.T
transpose

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [15]:
array = np.random.randint(10, 100, 15)
array


array([44, 85, 63, 55, 58, 72, 89, 59, 99, 90, 89, 28, 92, 74, 26])

In [18]:
array = np.where(array > 50, -1, array)
array

array([44, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28, -1, -1, 26])

In [19]:
count = np.sum(array == -1)
count

np.int64(12)

In [23]:
array = np.random.rand(5,4)
array

array([[0.23554011, 0.04876729, 0.4453258 , 0.13696099],
       [0.89603484, 0.24861166, 0.72000353, 0.4855253 ],
       [0.08739764, 0.47125619, 0.88053428, 0.60581903],
       [0.94787185, 0.23782776, 0.40081445, 0.36357731],
       [0.99684627, 0.79275593, 0.25168277, 0.09587543]])

In [24]:
row_sums = np.sum(array, axis=1)
max_row_index = np.argmax(row_sums)
array[max_row_index]

array([0.89603484, 0.24861166, 0.72000353, 0.4855253 ])

In [25]:
min = array.min(axis=1, keepdims=True)
max = array.max(axis=1, keepdims=True)
array_normalized = (array - min) / (max - min)
array_normalized

array([[0.47098427, 0.        , 1.        , 0.2223977 ],
       [1.        , 0.        , 0.72810472, 0.36593321],
       [0.        , 0.48397531, 1.        , 0.6536344 ],
       [1.        , 0.        , 0.22954446, 0.17710104],
       [1.        , 0.77347731, 0.17293272, 0.        ]])

In [28]:
arr = np.array([1,3,5,3,7,9,1,5,5])
array_unique = np.unique(arr)
array_unique

array([1, 3, 5, 7, 9])

In [29]:
elements, counts = np.unique(arr, return_counts=True)
duplicate_elements = elements[counts > 1]
duplicate_elements

array([1, 3, 5])

In [33]:
array = np.arange(1, 37)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [35]:
array = array.reshape(6,6)
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [36]:
array2 = array[1:5, 1:5]
array2

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [37]:
even_numbers = array2[array2 % 2 == 0]
even_numbers

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [41]:
array = np.arange(12)
array = array.reshape(3,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
array2 = array.reshape(2,6)
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [45]:
array3 = array2.flatten()
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
a = np.array([[1,2], [3,4]])
a = np.append(a,[[5,6]], axis = 0)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
a = np.append(a, [[7], [8], [9]], axis=1)
a

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [55]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
new_array = np.concatenate((a, b, c))
new_array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
new_array = new_array.reshape(3,3)
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
diagonal = np.diagonal(new_array)
diagonal

array([1, 5, 9])

In [58]:
array = np.arange(1,20)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [62]:
indices = np.where((array % 3 == 0) | (array % 5 == 0))
divisible = array[indices]
divisible

array([ 3,  5,  6,  9, 10, 12, 15, 18])

In [65]:
count = divisible.size
count

8

Pandas

In [67]:
import pandas as pd

In [68]:
data = pd.read_csv("/content/titanic_dataset.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [69]:
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [70]:
percentage = data.groupby('Sex')['Survived'].mean() * 100
percentage

,Survived
Sex,
female,74.203822
male,18.890815


In [72]:
mean_age = data['Age'].mean()
median_age = data['Age'].median()
std_age = data['Age'].std()

print(f"Mean:   {mean_age}")
print(f"Median: {median_age}")
print(f"Standard deviation:     {std_age}")

Mean:   29.69911764705882
Median: 28.0
Standard deviation:     14.526497332334044


In [74]:
no_of_passengers = data.groupby('Pclass').size()
no_of_passengers

,0
Pclass,
1,216
2,184
3,491


In [76]:
minor_females_survived = data[(data['Sex'] == 'female') & (data['Age'] < 18) & (data['Survived'] == 1)]
minor_females_survived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S


In [78]:
data['Age'] = data['Age'].fillna(data['Age'].median())
data
#data['Age'].isna().sum()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [80]:
def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

data['age_group'] = data['Age'].apply(categorize_age)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult


In [81]:
data.nlargest(5, 'Fare')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,Adult
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,Adult
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,Adult


In [82]:
average_fare = data.groupby(['Pclass', 'Sex'])['Fare'].mean()
average_fare

Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [84]:
data = data.rename(columns={'Sex': 'Gender', 'Fare': 'Ticket_fare'})
data

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult


In [85]:
survival_by_class = data.groupby(['Pclass', 'Survived']).size()
survival_by_class

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64

In [89]:
average_age = data.groupby(['Pclass', 'Gender'])['Age'].mean()
average_age

Pclass  Gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64